### ISSUE TITLE
Todo Sprint May 21 - May 31

### ISSUE THREAD

**Issue by aanchan** [aanchan/synap-epics#32]
Todo - Sprint 21-31 May, 2019
===

- [x] https://github.com/aanchan/synap_platform_backend/pull/199
- [x] https://github.com/aanchan/synap_sleep_chatbot/pull/61
- [ ] Bugfix Issue 174 : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_platform_backend/174
- [x] Bugfix Issue 198 : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_platform_backend/198
- [ ] Rasa Chatbot Update Evaluation script : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_sleep_chatbot/64
- [ ] Rasa Chatbot Environment variables : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_sleep_chatbot/42
- [ ] Rasa Chatbot Update endpoints.yml to read from end variables : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_sleep_chatbot/45
- [ ] Headers being stripped in Elastic Beanstalk deploys : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_platform_backend/141
- [x] Candidate interviews to update sleep-dashboard.
- [ ] Backend- health checks : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_platform_backend/144
- [ ] Cognito find a way to enforce unique email addresses : https://app.zenhub.com/workspaces/synaptitude-online-program-5c38fb274b3c9f05203b3b37/issues/aanchan/synap_platform_frontend/177
