### ISSUE TITLE
DB | Fixes for First Live Deployment

### ISSUE THREAD

**Issue by russellwjoel** [aanchan/synap-epics#36]
The intention is to add certain tickets to a db features and perform a fresh alembic history. Addressing some of the current db shortfalls. 

- [ ]  Remove javascript conventions (i.e. Camel) from python model definitions in db columns.
WeeklySleepReport.
 reportNumber | reportStartDate | reportEndDate 

- [ ] Rename:
WeeklySleepReport -> SleepReport.  ( Reports are not weekly. They are 7 days.) ??

- [ ] Add unique flag on columns -> questionnaire_sections.name, & resonse_values.name
- [ ]  FitbitToken, expires_in -> expires_at. Since it is not a lag time but an absolute time.

- [ ] Now that the applicaiton has many functional partitions it we should add pre fixes for specific tables. e.g. cognifit_ extend for . forms_ , fitbit_ . at the moment there is just sleep which is not very useful if were were to expand to a different device?? apply_sleep . fitbit_sleep? 

- [ ] nullable: defaultanswer, , questionSubText, dependant outcome
- [ ] remove unique constraint from answers: __table_args__ = (db.UniqueConstraint('question_response_id', 'user_id', name='_user_response'),) - (allows for multiple inserts of answers to the same questions.) . 
- [ ] change table name: question_options -> question_responses

### ORM

FitbitTokens . 
- [ ] should create_fitbit_tokens by plural ?  Why is this needed? just calls create. This should be removed. 

### GENERAL

- [ ] fitbit.tokens_profile.fitbit_top_level_models <- not a clear directory structure. 
- [ ] FitbitToken,  expires_in -> expires at.  Since it is not a lag time but an absolute time.

**Comment by russellwjoel** [comment]
User.user_name is not consistent with username used in views.

**Comment by russellwjoel** [comment]
camel case is used on some tables which makes psql annoying and is not consistent with the rest of the app

**Comment by russellwjoel** [comment]
Modify csv input methods to use cls.get_all() and a reference check to prevent duplicate inputs.

**Comment by russellwjoel** [comment]
standardize table names.   cognifit_<blah>     extend for . forms_<blah> ,    fitbit_<blah>

**Comment by russellwjoel** [comment]
change in_use to  is_active in  questions table

**Comment by russellwjoel** [comment]
return of default value is null

**Comment by russellwjoel** [comment]
nullable:   defaultanswer, ,  questionSubText,  dependant outcome

**Comment by russellwjoel** [comment]
make unique -> questionnaire_section

**Comment by russellwjoel** [comment]
organizations inherit from UpdateEntity instead of Entity.

**Comment by russellwjoel** [comment]
Answers remove
  # Unique Constraints
    __table_args__ = (db.UniqueConstraint('question_response_id', 'user_id', name='_user_response'),)

**Comment by russellwjoel** [comment]
question_options -> question_responses
