### ISSUE TITLE
API | Standardize View Definitions

### ISSUE THREAD

**Issue by russellwjoel** [aanchan/synap-epics#37]

**Comment by russellwjoel** [comment]
Endpoints:

### URLS
#### Pluralise Resources to be standard across all urls.
- [ ] user   -> users
- [x] questionnaire -> questionnaires

___
### Response Bodies

##### - questionnaire questions:
- [x] questionnaire -> questionnaireName
- [x]  section_name -> sectionName
- [x] section_title -> sectionTitle
- [x] positional_id -> positionalId
- [x] section_instructions -> sectionInstructions
- [x] section_required -> sectionRequired
- [x] dependent_outcome -> dependentOutcome
- [x] dependent_section -> dependentSection

- [x] reference_name -> questionId
- [x]  questionId
- [x]  positionalId
- [x]  questionText
- [x] questionSubtext
- [x] question_required -> questionRequired
- [x] answer_required -> answerRequired
- [x] allow_multiple_answers -> allowMultipleAnswers
- [x] dependent_question -> dependentQuestion
- [x] dependent_answer_value -> dependentAnswerValue
- [x] response_group -> responseGroup
- [x] input_type -> inputType
- [x] questionnaire_section -> questionnaireSection
- [x] response_options -> responseOptions
- [x] default_answer -> defaultAnswer


##### - questionnaire answers:
- [x]  questionnaire -> questionnaireName
- [x] reference_name -> questionId

error body.
- [x]  message -> error


___
### Method views:
- QuestionnaireView 
Flatten the main post body. 
Add class methods to raise errors. 

___
### Base View:
- Subsume the constructor into the base view.

**Comment by russellwjoel** [comment]
- [ ] Change Input Type return to be a KEY formatted:  KEY_STRING

**Comment by russellwjoel** [comment]
Decide on a success response:

{ "success": "true"} . ?

**Comment by russellwjoel** [comment]
user endpoint can remove the username parameter as instead all of the data for a user is taken from the token,

**Comment by russellwjoel** [comment]
add is_active check to all user action endpoints.

**Comment by russellwjoel** [comment]
add logging on all endpoints

**Comment by russellwjoel** [comment]
cognifit view ..  ErrorMessage =. User has not recorded enough Cognifit Skill Results .  -> . NO Cognifit Results

**Comment by russellwjoel** [comment]
remove auto genrate of json for all questionnaires.

**Comment by russellwjoel** [comment]
change user/profile . resource to somehting else?  - fitbitprofile?

**Comment by russellwjoel** [comment]
'/user/consent/<consent>', methods=['POST']) .   should be different.   

PUT request not post

resource /user/consent
